### ISSUE TITLE
Majority of controls (Outputs)  in the Profile no longer function.

### ISSUE THREAD

**Issue by MadKreator37** [HeliosProfiles/DCS-CH-47F-Profile-by-MadKreator37#2]
-MFD buttons seem to function
-ASE panel control function correctly

All other buttons/ switches/ levers receive input command but have no functioning outputs

-Using "BU Power switch", "engine start switch" and "OSPD switch" on the FADEC panel causes DCS to crash to desktop.

-certain controls are now popping circuit breakers

Inclined to believe ED may have made a mass change to the device command numbers.

Helios: 1.6.6110.005
DCS: 2.9.9.2280

**Comment by BlueFinBima** [comment]
This problem is related to the CH-47F interface and as such needs to be addressed by the HeliosVirtualCockpit/Helios project.  A new issue has been raised on this project https://github.com/HeliosVirtualCockpit/Helios/issues/846.
